TILE_SIZE = 32  # Px
CHUNK_SIZE = 10 # Tiles
REGION_SIZE = 14 # Chunks

DELTA_TIME = 0

WIDTH = 640     # Px
HEIGHT = 360    # Px

CHUNKS_SAVE_DELAY = 300 # Time in seconds

CHUNKS_SAVE_DELAY = CHUNKS_SAVE_DELAY * 60